theme: jekyll-theme-minimal
title: Tecnologia no dia a dia
description: Meu site pessoal para compartilhar conteúdo com todos. Bora bater um papo? Me adiciona no linkedin!!!
google_analytics: G-PJ2M60H4MQ
#https://github.com/pages-themes/cayman | https://github.com/pages-themes/minimal
#https://pages.github.com/themes/
