theme: jekyll-theme-midnight
title: Tecnologia no dia a dia
description: Meu site pessoal para compartilhar conteúdo com todos. Bora bater um papo? Me adiciona no linkedin!!!
google_analytics: UA-199275901-1
#https://github.com/pages-themes/cayman
#https://pages.github.com/themes/